version: 1.0
os: Linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: /dev/null
      timeout: 300
      runas: root
      script: |
        # Install Nginx
        sudo apt-get update
        sudo apt-get install -y nginx
  AfterInstall:
    - location: /dev/null
      timeout: 300
      runas: root
      script: |
        # Start Nginx
        sudo service nginix start
