version: 0.2

phases:
  install:
    
    runtime-versions:
      nodejs: 14
    
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y 

  pre_build:
    commands:
      - echo Starting Nginx...
      - sudo service nginx start  # Start Nginx service

  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/
  
  post_build:
    commands:
      - echo Stopping Nginx...
      - sudo service nginx stop 

artifacts:
  files:
    - '**/*'
